env:
  global:
    - $CACHE_DIR=$HOME/cache
    - PORT=1234
    - LUAROCKS=2.3.0
    - OPENSSL=1.0.2f
    - OPENRESTY=1.9.7.3

language: perl

before_install:
   - source ./setup.sh

before_script: ./start-test-server.sh

cache:
  directories:
    - $CACHE_DIR
